### ISSUE TITLE
Invalid Access Key Error when Using Natcorder to Record Unity Content in Flutter

### ISSUE THREAD

**Issue by Igniscode** [natmlx/natcorder#23]
Hello, I am writing to you as a representative of our company, which is considering incorporating Natcorder into our suite of services. Our primary goal is to utilize Natcorder's functionality to record the contents of Unity within our Flutter application.

After testing the integration of Natcorder with Unity, we have successfully recorded content without any issues. However, we have encountered an Invalid Access Key error when attempting to build exported Unity content in Flutter.

We would greatly appreciate any assistance you could provide in resolving this issue. Please let us know if there are any steps we can take or if we need to provide any additional information to assist you in troubleshooting the problem.

Thank you for your attention to this matter.

**Comment by olokobayusuf** [comment]
Hey there, this error happens when the app's bundle ID at runtime is different from the bundle ID that was set in Unity. This usually happens when you use Unity as a framework. The fix is to either ensure that the bundle ID in Unity's Player Settings matches the final bundle ID of your Flutter app, or to add a `NatMLBundle` attribute to any class in your project:
```csharp
using NatML.Hub;

[NatMLBundle("com.company.app")] // this should be the final bundle ID of your Flutter app
public class SomeComponent : MonoBehaviour {

}
```
